title: 'Adam Fistler'
name: 'Adam Fistler'
tagline: "Adam Fistler - Mind, Meaning & Transformation"

address:
  street: 'New Office Coming Soon'
  city: 'South Jersey / Philadelphia'
  state: 'NJ'
  zip: '08000'

bcc: '<a href="/html/main/contact_adam.html">Adam Fistler - Behavioral Change Consultant</a>'
contact_adam: '<a href="/html/main/contact_adam.html">Contact me</a>'
phone: '(609) 200-0230'
email: 'adam@adamfistler.com'

footer:
  - 'Copyright © 2026 - Adam Fistler Services - Camden, NJ. All Rights Reserved.'
  - 'Adam Fistler | New Office Coming Soon'
  - 'Serving South Jersey & Philadelphia with the latest in hypnosis, addiction alternatives, astrology, graphology, & technology.'
  - "South Jersey's Choice for Holistic Healing."

menu:
  Home: '/html/main/home.html'

  About Adam:
     area: 'adam'
     url: '/html/adam/landing.html'
     children:
       'Shyness / Anxiety': '/html/adam/early_childhood.html'
       'Addiction' : '/html/adam/addiction_development.html'

  Hypnosis:
    area: 'hypnosis'
    url: '/html/hypnosis/landing.html'
    children:
      Professional Experience: '/html/articles/hypnosis/bhc.html'
      About: '/html/hypnosis/about_hypnosis.html'
      FAQ: '/html/hypnosis/hypnosis_faq.html'
      Services: '/html/hypnosis/hypnosis_services.html'
      Why Can't I Change: '/html/hypnosis/wcic.html'
      Articles: '/html/articles/hypnosis/articles.html'
      Testimonials: '/html/hypnosis/testimonials.html'
      Addction: '/html/hypnosis/addiction_and_recovery.html'
      Anger: '/html/hypnosis/anger.html'
      Weight Loss: '/html/hypnosis/weight_loss.html'
      Smoking Cessation: '/html/hypnosis/smoking_cessation.html'

  Mindfulness:
    area: 'mindfulness'
    url: '/html/mindfulness/landing.html#mindfulness'
    children:
      FAQ: '/html/mindfulness/mindfulness_faq.html'

  Addiction & Recovery:
    area: 'addiction'
    url: '/html/addiction/landing.html#addiction'
    children:
      Approach & Services: '/html/addiction/addiction_services.html'
      Why Can't I Change: '/html/hypnosis/wcic.html'
      Hypnosis: '/html/hypnosis/addiction_and_recovery.html'
      FAQ: '/html/addiction/addiction_faq.html'
      Articles: '/html/articles/addiction/articles.html'

  Handwriting Analysis:
    area: 'handwriting_analysis'
    url: '/html/graphology/landing.html#handwriting_analysis'
    children:
      About: '/html/graphology/graphology.html'
      FAQ: '/html/graphology/graphology_faq.html'

  Astrology:
    area: 'astrology'
    url: '/html/astrology/landing.html#astrology'
    children:
      About: '/html/astrology/astrology.html'
      FAQ: '/html/astrology/astrology_faq.html'

  Technology:
    area: 'technology'
    url: '/html/technology/landing.html#technology'
    children:
      Projects: '/html/technology/projects.html'
      Artwork: '/html/technology/artwork.html'
      Resume: '/html/technology/resume.html'
      FAQ: '/html/technology/technology_faq.html'

  Groups & Workshops:
    area: 'groups'
    url: '/html/groups/landing.html#groups'
    children:
      Upcoming Events: '/html/groups/upcoming_events.html'

  Parties & Events:
    area: 'parties'
    url: '/html/parties/landing.html#parties'
    children:
      Scheduling: '/html/parties/scheduling.html'

  Contact Adam: '/html/main/contact_adam.html'

hypnosis:
  issue_columns: 4
  issues:
    - 'Adderall Abuse'
    - 'Addiction'
    - 'Alcohol Abuse'
    - 'Alcoholism'
    - 'Anger'
    - 'Anxiety'
    - 'Bad Habits'
    - 'Benzodiazepine Abuse'
    - 'Bruxism (Teeth Grinding)'
    - 'Cocaine Abuse'
    - 'Confidence'
    - 'Crack Abuse'
    - 'Diabetes'
    - 'Emotional Eating'
    - 'Exercise Habits'
    - 'Fatigue'
    - 'Fear of Failure'
    - 'Focus'
    - 'Forgiveness'
    - 'Grief Issues'
    - 'Guilt'
    - 'Headaches'
    - 'Heroin Abuse'
    - 'Heroin Addiction'
    - 'Hopelessness'
    - 'Hydrocodone (Vicodin) Abuse'
    - 'Irrational Fears (Phobias)'
    - 'Irritability'
    - 'Klonopin Abuse'
    - 'Laziness'
    - 'Methamphetamine Abuse'
    - 'Migraine Headaches'
    - 'Mood Swings'
    - 'Nail Biting'
    - 'Nose Picking'
    - 'Opiate / Opioid Abuse'
    - 'Oxycodone (Percocet) Abuse'
    - 'Pain Control / Pain Management'
    - 'Panic Attacks'
    - 'Procrastination'
    - 'Relationship Issues'
    - 'Relaxation'
    - 'Road Rage'
    - 'Self Discipline'
    - 'Self Esteem'
    - 'Self Image'
    - 'Self Sabotage'
    - 'Skin Problems'
    - 'Smoking Cessation'
    - 'Social Anxiety (Shyness)'
    - 'Stress'
    - 'Substance Abuse'
    - 'Stuttering'
    - 'Tension'
    - 'Test Anxiety'
    - 'Tiredness'
    - 'Trust Issues'
    - 'Weight Loss'
    - 'Worry'
    - 'Worthlessness'
    - 'Xanax Abuse'

keywords:
  - 'Addiction'
  - 'Substance Abuse'
  - 'Astrology'
  - 'Handwriting Analysis'
  - 'Technology'
  - 'Hypnosis'
  - 'Hypnotism'
  - 'Hypnotist'
  - 'Zodiac'
  - 'Natal Chart'
  - 'Birth Chart'
  - 'Birth Chart Reading'
  - 'Natal Chart Reading'
  - 'hypnosis'
  - 'hypnotist'
  - 'recovery'
  - 'addiction'
  - 'something else besides 12 step'
  - 'something else besides twleve step'
  - 'better than 12 step'
  - 'better than twelve step'
  - 'smart recovery'
  - 'different than 12 step'
  - 'different than twelve step'
  - 'hypnosis for addiction'
  - 'hypnosis for recovery'
  - 'addiction hypnosis'
  - 'recovery hypnosis'
  - 'South Jersey'
  - 'New Jersey'
  - 'Philadelphia'
  - "Absecon"
  - "08201"
  - "Alloway"
  - "08001"
  - "Ambler"
  - "19002"
  - "Ardmore"
  - "19003"
  - "Atco"
  - "08004"
  - "Atlantic City"
  - "08401"
  - "Audubon"
  - "08106"
  - "Bala Cynwyd"
  - "19004"
  - "Barrington"
  - "08007"
  - "Bellmawr"
  - "08031"
  - "Bensalem"
  - "19020"
  - "Berlin"
  - "08009"
  - "Beverly"
  - "08010"
  - "Blackwood"
  - "08012"
  - "Bordentown"
  - "08505"
  - "Bridgeport"
  - "08014"
  - "Bridgeton"
  - "08302"
  - "Bristol"
  - "19007"
  - "Broomall"
  - "19008"
  - "Bryn Mawr"
  - "19010"
  - "Burlington"
  - "08016"
  - "Camden"
  - "08102"
  - "Cedar Brook"
  - "08018"
  - "Chatsworth"
  - "08019"
  - "Cherry Hill"
  - "08002"
  - "Chesilhurst"
  - "08089"
  - "Chester"
  - "19013"
  - "Clarksboro"
  - "08020"
  - "Clayton"
  - "08312"
  - "Clementon"
  - "08021"
  - "Collingswood"
  - "08108"
  - "Columbus"
  - "08022"
  - "Conshohocken"
  - "19428"
  - "Croydon"
  - "19021"
  - "Darby"
  - "19023"
  - "Delran"
  - "08075"
  - "Deptford"
  - "08096"
  - "Doylestown"
  - "18901"
  - "Drexel Hill"
  - "19026"
  - "Egg Harbor City"
  - "08215"
  - "Egg Harbor Township"
  - "08234"
  - "Elkins Park"
  - "19027"
  - "Elmer"
  - "08318"
  - "Fairless Hills"
  - "19030"
  - "Florence"
  - "08518"
  - "Franklinville"
  - "08322"
  - "Gibbstown"
  - "08027"
  - "Glassboro"
  - "08028"
  - "Glendora"
  - "08029"
  - "Glenolden"
  - "19036"
  - "Gloucester City"
  - "08030"
  - "Haddonfield"
  - "08033"
  - "Haddon Heights"
  - "08035"
  - "Hammonton"
  - "08037"
  - "Havertown"
  - "19083"
  - "Jenkintown"
  - "19046"
  - "King of Prussia"
  - "19406"
  - "Lafayette Hill"
  - "19444"
  - "Lansdowne"
  - "19050"
  - "Levittown"
  - "19054"
  - "Lindenwold"
  - "08021"
  - "Lumberton"
  - "08048"
  - "Magnolia"
  - "08049"
  - "Mantua"
  - "08051"
  - "Marlton"
  - "08053"
  - "Media"
  - "19063"
  - "Medford"
  - "08055"
  - "Merchantville"
  - "08109"
  - "Mickleton"
  - "08056"
  - "Millville"
  - "08332"
  - "Moorestown"
  - "08057"
  - "Morrisville"
  - "19067"
  - "Mount Holly"
  - "08060"
  - "Mount Laurel"
  - "08054"
  - "Mullica Hill"
  - "08062"
  - "National Park"
  - "08063"
  - "New Castle"
  - "19720"
  - "New Lisbon"
  - "08064"
  - "Newtown"
  - "18940"
  - "Norristown"
  - "19401"
  - "Palmyra"
  - "08065"
  - "Paulsboro"
  - "08066"
  - "Pemberton"
  - "08068"
  - "Penndel"
  - "19047"
  - "Penns Grove"
  - "08069"
  - "Pennsauken"
  - "08110"
  - "Pennsville"
  - "08070"
  - "Philadelphia"
  - "19102"
  - "Pine Hill"
  - "08021"
  - "Pitman"
  - "08071"
  - "Plymouth Meeting"
  - "19462"
  - "Richwood"
  - "08074"
  - "Riverside"
  - "08075"
  - "Riverton"
  - "08077"
  - "Runnemede"
  - "08078"
  - "Salem"
  - "08079"
  - "Sewell"
  - "08080"
  - "Sicklerville"
  - "08081"
  - "Somerdale"
  - "08083"
  - "Southampton"
  - "08088"
  - "Springfield"
  - "19064"
  - "Swedesboro"
  - "08085"
  - "Thorofare"
  - "08086"
  - "Trenton"
  - "08608"
  - "Upper Darby"
  - "19082"
  - "Vineland"
  - "08360"
  - "Voorhees"
  - "08043"
  - "Wayne"
  - "19087"
  - "Wenonah"
  - "08090"
  - "West Chester"
  - "19380"
  - "Westville"
  - "08093"
  - "Williamstown"
  - "08094"
  - "Willingboro"
  - "08046"
  - "Wilmington"
  - "19801"
  - "Winslow"
  - "08095"
  - "Woodbury"
  - "08096"
  - "Woodbury Heights"
  - "08097"
  - "Woodstown"
  - "08098"
